Карпеченко Д.М., dz20, v.0.1, 04.01.2023

In [2]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import re
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
from mlxtend.preprocessing import TransactionEncoder

Перед началом модернизировал ручками исходный датасет - убрал пробелы, кучу запятых вконце чека, ибо намучался очень сильно

In [58]:
data = pd.read_csv(r'D:\TeachMeSkills\DZ\dz21\dataset2.csv', names=['Items'],delimiter='.')

In [59]:
data

                                                  Items
0     pork,sandwichbags,lunchmeat,all-purpose,flour,...
1     shampoo,handsoap,waffles,vegetables,cheeses,mi...
2     pork,soap,icecream,toiletpaper,dinnerrolls,han...
3          juice,lunchmeat,soda,toiletpaper,all-purpose
4     pasta,tortillas,mixes,handsoap,toiletpaper,veg...
...                                                 ...
1494  beef,sandwichbags,handsoap,papertowels,paperto...
1495  dinnerrolls,lunchmeat,spaghettisauce,pasta,veg...
1496  lunchmeat,eggs,poultry,vegetables,tortillas,be...
1497  ketchup,milk,poultry,cheeses,soap,toiletpaper,...
1498    laundrydetergent,vegetables,shampoo,vegetables,

[1499 rows x 1 columns]

In [60]:
data

                                                  Items
0     pork,sandwichbags,lunchmeat,all-purpose,flour,...
1     shampoo,handsoap,waffles,vegetables,cheeses,mi...
2     pork,soap,icecream,toiletpaper,dinnerrolls,han...
3          juice,lunchmeat,soda,toiletpaper,all-purpose
4     pasta,tortillas,mixes,handsoap,toiletpaper,veg...
...                                                 ...
1494  beef,sandwichbags,handsoap,papertowels,paperto...
1495  dinnerrolls,lunchmeat,spaghettisauce,pasta,veg...
1496  lunchmeat,eggs,poultry,vegetables,tortillas,be...
1497  ketchup,milk,poultry,cheeses,soap,toiletpaper,...
1498    laundrydetergent,vegetables,shampoo,vegetables,

[1499 rows x 1 columns]

In [61]:
data = data['Items'].reset_index(drop=True)

In [62]:
data

0       pork,sandwichbags,lunchmeat,all-purpose,flour,...
1       shampoo,handsoap,waffles,vegetables,cheeses,mi...
2       pork,soap,icecream,toiletpaper,dinnerrolls,han...
3            juice,lunchmeat,soda,toiletpaper,all-purpose
4       pasta,tortillas,mixes,handsoap,toiletpaper,veg...
                              ...
1494    beef,sandwichbags,handsoap,papertowels,paperto...
1495    dinnerrolls,lunchmeat,spaghettisauce,pasta,veg...
1496    lunchmeat,eggs,poultry,vegetables,tortillas,be...
1497    ketchup,milk,poultry,cheeses,soap,toiletpaper,...
1498      laundrydetergent,vegetables,shampoo,vegetables,
Name: Items, Length: 1499, dtype: object

In [65]:
data=data.transform(lambda x: x.split(','))

In [66]:
encoder = TransactionEncoder()
transactions = pd.DataFrame(encoder.fit(data).transform(data), columns=encoder.columns_)
display(transactions.head())

,,all-purpose,aluminumfoil,bagels,beef,butter,cereals,cheeses,coffee/tea,dinnerrolls,...,shampoo,soap,soda,spaghettisauce,sugar,toiletpaper,tortillas,vegetables,waffles,yogurt
0,False,True,True,False,True,True,False,False,False,True,...,True,False,True,False,False,False,False,True,False,False
1,False,False,False,False,False,False,False,True,False,False,...,True,False,False,False,False,False,False,True,True,False
2,False,False,False,False,False,False,False,False,False,True,...,False,True,False,True,False,True,False,False,False,False
3,False,True,False,False,False,False,False,False,False,False,...,False,False,True,False,False,True,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,True,True,False,False

In [67]:
transactions.drop(transactions.columns[[0]], axis = 1)

,all-purpose,aluminumfoil,bagels,beef,butter,cereals,cheeses,coffee/tea,dinnerrolls,dishwashingliquid/detergent,...,shampoo,soap,soda,spaghettisauce,sugar,toiletpaper,tortillas,vegetables,waffles,yogurt
0,True,True,False,True,True,False,False,False,True,False,...,True,False,True,False,False,False,False,True,False,False
1,False,False,False,False,False,False,True,False,False,True,...,True,False,False,False,False,False,False,True,True,False
2,False,False,False,False,False,False,False,False,True,False,...,False,True,False,True,False,True,False,False,False,False
3,True,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,True,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,True,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1494,True,False,False,True,False,False,True,True,False,False,...,True,False,False,False,False,False,False,False,False,False
1495,False,False,False,False,False,True,True,False,True,False,...,False,True,False,True,False,False,False,True,False,False
1496,False,False,False,True,False,False,False,False,False,True,...,True,False,False,False,True,False,True,True,False,False
1497,True,False,False,True,False,False,True,False,False,False,...,False,True,False,True,True,True,False,False,True,True
1498,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,True,False,False

In [68]:
transactions.shape

(1499, 39)

In [69]:
frequent_itemsets = apriori(transactions, min_support= 6/len(data), use_colnames=True, max_len =3)
rules = association_rules(frequent_itemsets, metric="lift",  min_threshold = 1.5)
display(rules.head(20))
print("Rules identified: ", len(rules))

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,"(tortillas, aluminumfoil)",(sandwichloaves),0.058706,0.248833,0.022015,0.375000,1.507038,0.007407,1.201868
1,(sandwichloaves),"(tortillas, aluminumfoil)",0.248833,0.058706,0.022015,0.088472,1.507038,0.007407,1.032655
2,"(beef, cheeses)",(sandwichbags),0.066711,0.250167,0.025350,0.380000,1.518987,0.008661,1.209408
3,(sandwichbags),"(beef, cheeses)",0.250167,0.066711,0.025350,0.101333,1.518987,0.008661,1.038526
4,"(beef, mixes)",(pork),0.065377,0.250167,0.025350,0.387755,1.549986,0.008995,1.224728
5,(pork),"(beef, mixes)",0.250167,0.065377,0.025350,0.101333,1.549986,0.008995,1.040011
6,"(sandwichloaves, cheeses)",(soap),0.064710,0.265510,0.026017,0.402062,1.514298,0.008836,1.228371
7,(soap),"(sandwichloaves, cheeses)",0.265510,0.064710,0.026017,0.097990,1.514298,0.008836,1.036896
8,"(dishwashingliquid/detergent, spaghettisauce)",(fruits),0.061374,0.263509,0.025350,0.413043,1.567474,0.009178,1.254762
9,(fruits),"(dishwashingliquid/detergent, spaghettisauce)",0.263509,0.061374,0.025350,0.096203,1.567474,0.009178,1.038535
10,"(toiletpaper, flour)",(soap),0.062708,0.265510,0.025350,0.404255,1.522560,0.008700,1.232893
11,(soap),"(toiletpaper, flour)",0.265510,0.062708,0.025350,0.095477,1.522560,0.008700,1.036228
12,"(juice, mixes)",(ketchup),0.071381,0.250167,0.027352,0.383178,1.531688,0.009494,1.215639
13,(ketchup),"(juice, mixes)",0.250167,0.071381,0.027352,0.109333,1.531688,0.009494,1.042611
14,"(sandwichloaves, pork)",(juice),0.060707,0.257505,0.024016,0.395604,1.536298,0.008384,1.228492
15,(juice),"(sandwichloaves, pork)",0.257505,0.060707,0.024016,0.093264,1.536298,0.008384,1.035906
16,"(sandwichloaves, yogurt)",(juice),0.064043,0.257505,0.026017,0.406250,1.577639,0.009526,1.250518
17,(juice),"(sandwichloaves, yogurt)",0.257505,0.064043,0.026017,0.101036,1.577639,0.009526,1.041151
18,"(laundrydetergent, tortillas)",(ketchup),0.059373,0.250167,0.022682,0.382022,1.527071,0.007829,1.213366
19,(ketchup),"(laundrydetergent, tortillas)",0.250167,0.059373,0.022682,0.090667,1.527071,0.007829,1.034414

Rules identified:  22